version: '3'

services:
  web-test:
    image: nginx
    container_name: nkay.info-web-test
    restart: unless-stopped
    volumes:
#      - ./nginx.conf/:/etc/nginx/nginx.conf:ro
      - ./html-test:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - VIRTUAL_PORT=443
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
#    depends_on:
#      - proxy
    networks:
      - proxy
#      - default

networks:
  proxy:
    external:
      name: nginx_network
